### PR TITLE
Updates on code

### PR DESCRIPTION
**Pull request by desiRadkova**
Hi Sharks,

I hope your weekend is going well! :) 
Could you please review my work and leave me a comment about it?

### CODE REVIEW

**Comment by Tuscann** [comment]
Add git ignore file.

**Comment by Tuscann** [comment]
It is fine by me.
Lets somebody else from the team to approve pull request.

**Review by Tuscann — APPROVED** [review]
Good effort.
Keep learning.

**Review by Irida0 — APPROVED** [review]
Looks fine by me too. :)

**Comment by VladiBoz** [comment]
Gj

**Pull request merged**
